production:
  billing_invoices:
    class: TenantSwitchEachJob
    args: [Scheduled::BillingMembersInvoicerJob]
    queue: low
    schedule: at 5am every day

  billing_shop_orders:
    class: TenantSwitchEachJob
    args: [Scheduled::BillingShopOrdersAutoInvoicerJob]
    queue: low
    schedule: at 4:45am every day

  billing_payments:
    class: TenantSwitchEachJob
    args: [Scheduled::BillingPaymentsProcessorJob]
    queue: low
    schedule: at 4am every day

  billing_local_currency_payments:
    class: TenantSwitchEachJob
    args: [Scheduled::BillingLocalCurrencyPaymentsProcessorJob]
    queue: low
    schedule: at 4am every day

  billing_sepa_direct_debit_orders_upload:
    class: TenantSwitchEachJob
    args: [Scheduled::BillingSEPADirectDebitOrdersUploaderJob]
    queue: low
    schedule: at 4:15am every day

  billing_snapshot:
    class: TenantSwitchEachJob
    args: [Scheduled::BillingSnapshotJob]
    queue: low
    schedule: "0 45-59/1 23 28-31 * *" # last 15 minutes of each quarter

  newsletters_sender:
    class: TenantSwitchEachJob
    args: [Scheduled::NewslettersSenderJob]
    queue: low
    schedule: at 3:00am every day

  chores:
    class: TenantSwitchEachJob
    args: [Scheduled::ChoresJob]
    queue: low
    schedule: at midnight every day

  notifier_daily:
    class: TenantSwitchEachJob
    args: [Scheduled::NotifierDailyJob]
    queue: low
    schedule: at 4:30am every day

  notifier_hourly:
    class: TenantSwitchEachJob
    args: [Scheduled::NotifierHourlyJob]
    queue: low
    schedule: every hour

  postmark_sync_suppressions:
    class: TenantSwitchEachJob
    args: [Scheduled::PostmarkSyncSuppressionsJob]
    queue: low
    schedule: every hour

  postmark_sync_deliveries:
    class: TenantSwitchEachJob
    args: [Scheduled::PostmarkSyncDeliveriesJob]
    queue: low
    schedule: every hour

  absences_included_reminder:
    class: TenantSwitchEachJob
    args: [Scheduled::AbsencesIncludedReminderJob]
    queue: low
    schedule: at 6am every day

  members_anonymizer:
    class: TenantSwitchEachJob
    args: [Scheduled::MembersAnonymizerJob]
    queue: low
    schedule: at 3:30am every day

  mail_deliveries_purge:
    class: TenantSwitchEachJob
    args: [Scheduled::MailDeliveriesPurgeJob]
    queue: low
    schedule: at 1am every day

  search_prune:
    class: TenantSwitchEachJob
    args: [Scheduled::SearchPruneJob]
    queue: low
    schedule: at 0:30am every day

  search_rebuild:
    class: TenantSwitchEachJob
    args: [Scheduled::SearchRebuildJob]
    queue: low
    schedule: every sunday at 2am

  demo_reset:
    class: Demo::ResetJob
    queue: low
    schedule: every monday at 2am
