production: &production
  ragedevert:
    admin_host: admin.ragedevert.ch
    members_host: membres.ragedevert.ch
  lumieredeschamps:
    admin_host: admin.lumiere-des-champs.ch
    members_host: membres.lumiere-des-champs.ch
  tapatate:
    admin_host: admin.tapatate.ch
    members_host: membres.tapatate.ch
  clefdeschamps:
    admin_host: admin.clef-des-champs.ch
    members_host: membres.clef-des-champs.ch
  croquterre:
    admin_host: admin.croquterre.ch
    members_host: membres.croquterre.ch
  alabellecourgette:
    admin_host: admin.alabellecourgette.ch
    members_host: membres.alabellecourgette.ch
  lesjardinsdouchy:
    admin_host: admin.lesjardinsdouchy.ch
    members_host: membres.lesjardinsdouchy.ch
    aliases:
      - jardinsdouchy
      - ouchy
  lamule:
    admin_host: admin.lamule.ch
    members_host: membres.lamule.ch
    aliases:
      - mule
  lafermedugoupil:
    admin_host: admin.lafermedugoupil.ch
    members_host: membres.lafermedugoupil.ch
    aliases:
      - fermedugoupil
      - goupil
  lafermedessavanes:
    admin_host: admin.lafermedessavanes.ch
    members_host: membres.lafermedessavanes.ch
    aliases:
      - fermedessavanes
      - savanes
  seminterra:
    admin_host: admin.seminterra.ch
    members_host: soci.seminterra.ch
  p2r:
    admin_host: admin.p2r.ch
    members_host: membres.p2r.ch
  grundnahrig:
    admin_host: admin.grundnahrig.ch
    members_host: mitglieder.grundnahrig.ch
  jardindesturricules:
    admin_host: admin.jardindesturricules.ch
    members_host: membres.jardindesturricules.ch
    aliases:
      - turricules
  lepetitsecheron:
    admin_host: admin.lepetitsecheron.ch
    members_host: membres.lepetitsecheron.ch
    aliases:
      - petitsecheron
      - secheron
  paniersdesavigny:
    admin_host: admin.paniersdesavigny.ch
    members_host: membres.paniersdesavigny.ch
    aliases:
      - savigny
  cocagne:
    admin_host: admin.cocagne.ch
    members_host: membres.cocagne.ch
  potagersdegaia:
    admin_host: admin.potagersdegaia.ch
    members_host: membres.potagersdegaia.ch
    aliases:
      - gaia
  latouviere:
    admin_host: admin.touviere.ch
    members_host: membres.touviere.ch
    aliases:
      - touviere
  alpgrava:
    admin_host: admin.alpgrava.ch
    members_host: membres.alpgrava.ch
  filierealimentaire:
    admin_host: admin.filierealimentaire.ch
    members_host: membres.filierealimentaire.ch
    aliases:
      - locali
      - paniers-cap
      - cap
  fermedesverpilleres:
    admin_host: admin.ferme-des-verpilleres.ch
    members_host: membres.ferme-des-verpilleres.ch
    aliases:
      - verpilleres
      - aresetvous
  hofnarr:
    admin_host: admin.hof-narr.ch
    members_host: mitglieder.hof-narr.ch
  lejardindemax:
    admin_host: admin.lejardindemax.ch
    members_host: membres.lejardindemax.ch
    aliases:
      - jardindemax
      - max
  cultureslocales:
    admin_host: admin.cultureslocales.ch
    members_host: membres.cultureslocales.ch
  lepetrichor:
    admin_host: admin.lepetrichor.ch
    members_host: membres.lepetrichor.ch
    aliases:
      - petrichor
  ortie:
    admin_host: admin.ortie-microferme.ch
    members_host: membres.ortie-microferme.ch
    aliases:
      - microferme-ortie
  fairdura:
    admin_host: admin.fairdura.ch
    members_host: mitglieder.fairdura.ch
  wilderauke:
    admin_host: admin.wilde-rauke.de
    members_host: mitglieder.wilde-rauke.de
  baieattitude:
    admin_host: admin.baie-attitude.ch
    members_host: membres.baie-attitude.ch
  boisdunant:
    admin_host: admin.ferme-boisdunant.ch
    members_host: membres.ferme-boisdunant.ch
  lamilpadesiles:
    admin_host: admin.lamilpadesiles.ch
    members_host: membres.lamilpadesiles.ch
    aliases:
      - milpadesiles

  mamajah:
    admin_host: admin.mamajah.org
    members_host: membres.mamajah.org
    state: onboarding
  racine2:
    admin_host: admin.racine2.ch
    members_host: membres.racine2.ch
    state: onboarding
  stadsgroenteboer:
    admin_host: admin.stadsgroenteboer.nl
    members_host: members.stadsgroenteboer.nl
    state: onboarding
  chevreetchou:
    admin_host: admin.chevreetchou.ch
    members_host: membres.chevreetchou.ch
    state: onboarding
  radisnoir:
    admin_host: admin.radis-noir.ch
    members_host: membres.radis-noir.ch
    state: onboarding
  querbeet:
    admin_host: admin.querbeetgrosswangen.com
    members_host: mitglieder.querbeetgrosswangen.com
    state: onboarding
  monniati:
    admin_host: admin.lafermedumonniati.ch
    members_host: membres.lafermedumonniati.ch
    state: onboarding
    aliases:
      - fermedumonniati
      - lafermedumonniati

  demo-fr:
    admin_host: admin.acp-admin.ch
    members_host: membres.acp-admin.ch
    state: custom
  demo-en:
    admin_host: admin.csa-admin.org
    members_host: members.csa-admin.org
    state: custom
  demo-de:
    admin_host: admin.solawi-admin.org
    members_host: mitglieder.solawi-admin.org
    state: custom

  microfermes:
    admin_host: admin.microfermes.ch
    members_host: membres.microfermes.ch
    state: custom

development:
  <<: *production

test:
  acme:
    admin_host: admin.acme.test
    members_host: members.acme.test
    aliases:
      - ac
